apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-u6st
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-u6st
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-u6st
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-u6st
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-u6st
    spec:
      containers:
      - image: quay.io/mbasti-test-org/happy-path-wonj-tenant/appstudio/dc-metro-map-u6st@sha256:626b7711693f6e9016346c59e7851b18fa4227cdb9c6664fad67d7bbf52db37b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
